### ISSUE TITLE
Error while fetching version

### ISSUE THREAD

**Issue by mdmusaibali** [powenn/AltServer-Linux-PyScript#31]
python3 main.py 
version.json not exists
Fetching version ...
Traceback (most recent call last):
  File "/home/mdmusaibali/Desktop/Altserver/AltServer-Linux-PyScript-1.0.2/main.py", line 530, in <module>
    main()
  File "/home/mdmusaibali/Desktop/Altserver/AltServer-Linux-PyScript-1.0.2/main.py", line 434, in main
    CheckResource()
  File "/home/mdmusaibali/Desktop/Altserver/AltServer-Linux-PyScript-1.0.2/main.py", line 139, in CheckResource
    latest_version_json: dict = FetchVersion()
  File "/home/mdmusaibali/Desktop/Altserver/AltServer-Linux-PyScript-1.0.2/main.py", line 104, in FetchVersion
    "https://api.github.com/repos/NyaMisty/AltServer-Linux/releases/latest", headers=headers if CUSTOM_HEADERS_ENABLED else "").json()["tag_name"]
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

**Comment by mdmusaibali** [comment]
cat /etc/os-release 
NAME="Zorin OS"
VERSION="16.3"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 16.3"
VERSION_ID="16"
HOME_URL="https://zorin.com/os/"
SUPPORT_URL="https://help.zorin.com/"
BUG_REPORT_URL="https://zorin.com/os/feedback/"
PRIVACY_POLICY_URL="https://zorin.com/legal/privacy/"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by powenn** [comment]
Did you run this script frequently in short time 

https://github.com/powenn/AltServer-Linux-PyScript/issues/25

**Comment by mdmusaibali** [comment]
I did not. Seeing this error since first time.

**Comment by powenn** [comment]
python version ?

**Comment by mdmusaibali** [comment]
3.10
